/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JRadioButton;
import modelo.Opcion;
import modelo.PersitenciaPregunta;
import modelo.Pregunta;

/**
 *
 * @author juan_
 */
public class TestAplicacion extends javax.swing.JFrame {
int numero=0;
int tiempo=0;
    /**
     * Creates new form TestAplicacion
     */
    public TestAplicacion() {
        initComponents();
        setLocationRelativeTo(this);
        setSize(300, 500);
        mostrarPregunta(numero++); 
        Thread t1=new Thread(new Runnable() {
            @Override
            public void run() {
        while(true){
            tiempo++;
            try {
                Thread.sleep(1000);
                etiquetaTiempo.setText(""+tiempo);
                if(tiempo>=30)mostrarPregunta(numero++);
            } catch (InterruptedException ex) {
            }
        }
            }
        });
        t1.start();
        
    }
    public void mostrarPregunta(int numero){
        tiempo=0;
        try {
            //Primero sacamos la pregunta del numero dado
            ArrayList<Pregunta> preguntas=PersitenciaPregunta.leer();
            Pregunta p=preguntas.get(numero);
            //Ajustamos los valores
            //Primero va el titulo
               etiquetaPregunta.setText(p.getTitulo());
              //Ahora las opciones
              ArrayList<Opcion> opciones =p.getOpciones();
              //Aplicamos el algoritmo
               opciones=    PersitenciaPregunta.opcionesAleatorias(opciones);
              rb1Si.setText(opciones.get(0).getTitulo());
              rb2No.setText(opciones.get(1).getTitulo());
              rb3poco.setText(opciones.get(2).getTitulo());
              rb4ninguna.setText(opciones.get(3).getTitulo());
        } catch (Exception ex) {
         
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        etiquetaTiempo = new javax.swing.JLabel();
        etiquetaPregunta = new javax.swing.JLabel();
        rb1Si = new javax.swing.JRadioButton();
        rb2No = new javax.swing.JRadioButton();
        rb3poco = new javax.swing.JRadioButton();
        rb4ninguna = new javax.swing.JRadioButton();
        Siguiente = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Contestar Test");
        getContentPane().add(jLabel1);

        etiquetaTiempo.setText("TIEMPO");
        getContentPane().add(etiquetaTiempo);

        etiquetaPregunta.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        etiquetaPregunta.setText("Sabes como se creo la primera pelicula en cine?");
        getContentPane().add(etiquetaPregunta);

        buttonGroup1.add(rb1Si);
        rb1Si.setText("si");
        rb1Si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1SiActionPerformed(evt);
            }
        });
        getContentPane().add(rb1Si);

        buttonGroup1.add(rb2No);
        rb2No.setText("no");
        rb2No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2NoActionPerformed(evt);
            }
        });
        getContentPane().add(rb2No);

        buttonGroup1.add(rb3poco);
        rb3poco.setText("muy poco");
        getContentPane().add(rb3poco);

        buttonGroup1.add(rb4ninguna);
        rb4ninguna.setText("ninguna de las primeras opcines");
        getContentPane().add(rb4ninguna);

        Siguiente.setText("Siguiente pregunta >>");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(Siguiente);

        jButton2.setText("Terminar Test");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        // TODO add your handling code here:
         
         mostrarPregunta(numero++);
         
    }//GEN-LAST:event_SiguienteActionPerformed

    private void rb1SiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1SiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1SiActionPerformed

    private void rb2NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2NoActionPerformed
          // TODO add your handling code here:
          
    }//GEN-LAST:event_rb2NoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestAplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Siguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel etiquetaPregunta;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rb1Si;
    private javax.swing.JRadioButton rb2No;
    private javax.swing.JRadioButton rb3poco;
    private javax.swing.JRadioButton rb4ninguna;
    // End of variables declaration//GEN-END:variables
}
